### ISSUE TITLE
What exactly you are programming here? Wiki or Game?

### ISSUE THREAD

**Issue by a1aw** [Diorite/Diorite.org#1]
I forked the project and had a view of it.
This is a Dynamic Web Project. But I found that.... snake game?

If you are going to write a wiki, I have designer tools to make webpages quickly.

**Comment by GotoFinal** [comment]
I'm just trying to learn some javaEE, GWT and other stuff here, so I can try make some website for project, or maybe even: I trying to make this website to learn about JavaEE and GWT.

I created snake to learn some basic of GWT.

**Comment by a1aw** [comment]
Probably this "question" issue can be closed now.
